version: '3.1'

services:
  app:
    container_name: scheduler
    build: scheduler
    environment:
      FTX_KEY: ${FTX_KEY}
      FTX_SECRET: ${FTX_SECRET}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    restart: unless-stopped
  api:
    container_name: api
    build: api
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongo
    ports:
      - 0.0.0.0:80:8080
    restart: unless-stopped
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
    restart: unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  